# Generated by Django 3.2.7 on 2022-11-29 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('issue_limit', models.DateField(blank=True, null=True, verbose_name='発行期限')),
                ('alarm_content', models.CharField(max_length=40, verbose_name='アラート内容')),
            ],
            options={
                'verbose_name_plural': 'AlarmHistory',
            },
        ),
        migrations.CreateModel(
            name='HospitalApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, verbose_name='病院名')),
                ('address', models.CharField(max_length=120, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=12, verbose_name='電話番号')),
                ('director_name', models.CharField(max_length=40, verbose_name='責任者名')),
                ('licence_copy', models.ImageField(upload_to='', verbose_name='獣医師免許写し')),
            ],
            options={
                'verbose_name_plural': 'HospitalApply',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateField(blank=True, null=True, verbose_name='ログイン日')),
                ('login_limit', models.DateField(blank=True, null=True, verbose_name='ログインの有効期限')),
                ('logout_flag', models.CharField(max_length=1, verbose_name='ログアウトフラグ')),
                ('distinction_flag', models.CharField(max_length=1, verbose_name='一般、病院判別フラグ')),
            ],
            options={
                'verbose_name_plural': 'LoginHistory',
            },
        ),
        migrations.CreateModel(
            name='MasterHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, verbose_name='病院名')),
                ('address', models.CharField(max_length=120, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=12, verbose_name='電話番号')),
                ('director_name', models.CharField(max_length=40, verbose_name='責任者名')),
            ],
            options={
                'verbose_name_plural': 'MasterHospital',
            },
        ),
        migrations.CreateModel(
            name='MasterHospitalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=7, verbose_name='病院ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'verbose_name_plural': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='MasterMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(max_length=40, verbose_name='お薬情報')),
            ],
            options={
                'verbose_name_plural': 'MasterMedicine',
            },
        ),
        migrations.CreateModel(
            name='MasterPrefectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefectures', models.CharField(max_length=4, verbose_name='都道府県')),
            ],
            options={
                'verbose_name_plural': 'MasterPrefectures',
            },
        ),
        migrations.CreateModel(
            name='MasterVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(max_length=40, verbose_name='ワクチン種類')),
            ],
            options={
                'verbose_name_plural': 'MasterVaccination',
            },
        ),
        migrations.CreateModel(
            name='QRcodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('issue_limit', models.DateField(blank=True, null=True, verbose_name='発行期限')),
            ],
            options={
                'verbose_name_plural': 'QRcodeHistory',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='個体番号')),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 29, 5, 8, 6, 850372, tzinfo=utc), verbose_name='接種日付')),
                ('hospital_id', models.CharField(blank=True, max_length=7, null=True, verbose_name='病院ID')),
                ('vaccination_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogcat.mastervaccination', verbose_name='接種ワクチン')),
            ],
            options={
                'verbose_name_plural': 'Vaccination',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=11, verbose_name='ペットID')),
                ('taking_date', models.DateField(verbose_name='飲む日付け')),
                ('create_date', models.DateField(blank=True, default=datetime.datetime(2022, 11, 29, 5, 8, 6, 860938, tzinfo=utc), verbose_name='作成日付')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='最終更新日')),
                ('medicine_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogcat.mastermedicine', verbose_name='服用薬')),
            ],
            options={
                'verbose_name_plural': 'Medicine',
            },
        ),
    ]
