# Generated by Django 3.2.7 on 2023-02-13 06:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, verbose_name='病院名')),
                ('address', models.CharField(max_length=120, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]*$', '数字のみを入力してください。')], verbose_name='電話番号')),
                ('director_name', models.CharField(max_length=40, verbose_name='責任者名')),
                ('licence_copy', models.ImageField(upload_to='', verbose_name='獣医師免許写し')),
            ],
            options={
                'verbose_name_plural': 'HospitalApply',
            },
        ),
        migrations.CreateModel(
            name='MasterGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=2, verbose_name='性別')),
            ],
            options={
                'verbose_name_plural': 'MasterGender',
            },
        ),
        migrations.CreateModel(
            name='MasterHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, verbose_name='病院名')),
                ('address', models.CharField(max_length=120, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=12, verbose_name='電話番号')),
                ('director_name', models.CharField(max_length=40, verbose_name='責任者名')),
            ],
            options={
                'verbose_name_plural': 'MasterHospital',
            },
        ),
        migrations.CreateModel(
            name='MasterHospitalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=7, verbose_name='病院ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'verbose_name_plural': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='MasterMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(max_length=40, verbose_name='お薬情報')),
            ],
            options={
                'verbose_name_plural': 'MasterMedicine',
            },
        ),
        migrations.CreateModel(
            name='MasterVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(max_length=40, verbose_name='ワクチン種類')),
            ],
            options={
                'verbose_name_plural': 'MasterVaccination',
            },
        ),
        migrations.CreateModel(
            name='QRcodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('issue_limit', models.DateField(blank=True, null=True, verbose_name='発行期限')),
            ],
            options={
                'verbose_name_plural': 'QRcodeHistory',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15, '個体番号は15文字です。'), django.core.validators.RegexValidator('^[0-9]*$', '数字のみを入力してください。')], verbose_name='個体番号')),
                ('date', models.DateField(default=datetime.datetime(2023, 2, 13, 6, 12, 42, 174618, tzinfo=utc), verbose_name='接種日付')),
                ('hospital_id', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7, '病院IDは7文字です。'), django.core.validators.RegexValidator('^[0-9]*$', '数字のみを入力してください。')], verbose_name='病院ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='飼い主名')),
                ('owner_address', models.CharField(max_length=255, verbose_name='住所')),
                ('pet_name', models.CharField(max_length=100, verbose_name='ペット名')),
                ('species', models.CharField(max_length=30, verbose_name='種別')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogcat.mastergender', verbose_name='性別')),
                ('vaccination_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogcat.mastervaccination', verbose_name='接種ワクチン')),
            ],
            options={
                'verbose_name_plural': 'Vaccination',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=11, verbose_name='ペットID')),
                ('taking_date', models.DateField(verbose_name='飲む日付')),
                ('create_date', models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 6, 12, 42, 177610, tzinfo=utc), verbose_name='作成日付')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='最終更新日')),
                ('medicine_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogcat.mastermedicine', verbose_name='服用薬')),
            ],
            options={
                'verbose_name_plural': 'Medicine',
            },
        ),
    ]
