# Generated by Django 3.2.7 on 2022-10-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='個体番号')),
                ('data', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('vaccination', models.CharField(max_length=255, verbose_name='接種ワクチン')),
                ('hospitalid', models.CharField(blank=True, max_length=255, null=True, verbose_name='病院ID')),
            ],
            options={
                'verbose_name_plural': 'Dogcat',
            },
        ),
    ]
