# Generated by Django 3.2.7 on 2022-11-08 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dogcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 0, 39, 42, 645001, tzinfo=utc), verbose_name='接種日付'),
        ),
    ]
