# Generated by Django 3.2.7 on 2022-10-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='mc_number',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='個体番号'),
        ),
    ]
