# Generated by Django 3.2.7 on 2022-10-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcat',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='個体番号'),
        ),
    ]
