# Generated by Django 3.2.7 on 2022-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcat', '0002_alter_dogcat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination', models.CharField(max_length=255, verbose_name='接種ワクチン')),
            ],
            options={
                'verbose_name_plural': 'MasterVaccination',
            },
        ),
        migrations.RenameModel(
            old_name='Dogcat',
            new_name='Vaccination',
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name_plural': 'Vaccination'},
        ),
    ]
