# Generated by Django 3.2.7 on 2022-11-07 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dogcat', '0002_alter_vaccination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 7, 7, 19, 50, 619159, tzinfo=utc), verbose_name='接種日付'),
        ),
    ]
