# Generated by Django 3.2.7 on 2022-11-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcat', '0002_alter_vaccination_mc_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='ユーザID')),
                ('mc_number', models.CharField(max_length=15, verbose_name='個体番号')),
                ('user_password', models.CharField(max_length=16, verbose_name='パスワード')),
                ('user_birthday', models.DateField(verbose_name='生年月日')),
                ('pet_id', models.CharField(max_length=11, verbose_name='ペットID')),
                ('pet_name', models.CharField(max_length=40, verbose_name='名前')),
                ('createdate', models.DateField(blank=True, null=True, verbose_name='作成日付')),
                ('updatedate', models.DateField(blank=True, null=True, verbose_name='最終更新日')),
            ],
            options={
                'verbose_name_plural': 'MasterUser',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='mastermedicine',
            name='pet_id',
        ),
        migrations.RemoveField(
            model_name='mastermedicine',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='mastermedicine',
            name='user_birthday',
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='mc_number',
            field=models.BigIntegerField(blank=True, max_length=15, null=True, verbose_name='個体番号'),
        ),
    ]
