# Generated by Django 3.2.7 on 2022-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcat', '0006_alter_vaccination_mc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='mc_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='個体番号'),
        ),
    ]
